# Generated by Django 4.0.6 on 2022-07-22 19:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='posts',
            name='image_url',
            field=models.CharField(blank=True, db_index=True, default='img/error.png', max_length=150, null=True, verbose_name='Image'),
        ),
    ]
