# Generated by Django 4.0.6 on 2022-07-23 20:02

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0002_posts_image_url'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='posts',
            name='image_url',
        ),
        migrations.AddField(
            model_name='posts',
            name='image',
            field=cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='image'),
        ),
    ]
