# Generated by Django 4.0.6 on 2022-07-23 21:04

import cloudinary.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0003_remove_posts_image_url_posts_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(db_index=True, default='Anonymus', max_length=14, verbose_name='Name')),
                ('body', models.CharField(blank=True, db_index=True, max_length=150, null=True, verbose_name='Body')),
                ('image', cloudinary.models.CloudinaryField(blank=True, max_length=255, null=True, verbose_name='Image')),
                ('date', models.DateField(auto_now_add=True, verbose_name='Date')),
            ],
        ),
        migrations.DeleteModel(
            name='Posts',
        ),
    ]
