# Generated by Django 4.0.6 on 2022-07-29 19:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0007_alter_post_date'),
    ]

    operations = [
        migrations.CreateModel(
            name='User_data',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.CharField(max_length=20, verbose_name='User id')),
                ('liked_post_id', models.IntegerField(default='000x', verbose_name='Liked post id')),
            ],
        ),
    ]
