# Generated by Django 4.0.6 on 2022-07-29 20:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('posts', '0008_user_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_data',
            name='liked_post_id',
            field=models.IntegerField(default=0, verbose_name='Liked_post_id'),
        ),
        migrations.AlterField(
            model_name='user_data',
            name='user_id',
            field=models.CharField(max_length=20, verbose_name='User_id'),
        ),
    ]
